In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
#cite: https://www.kaggle.com/selfishgene/nothing-fancy-just-some-heuristics-0-9374

In [8]:
#%% load data
print('loading data...')

farmerPref = pd.read_csv('Farmer_preferences1.csv', header=None).as_matrix()[:, 1:]
buyerPref = pd.read_csv('Buyer_preferences.csv' , header=0).as_matrix()#[:, 1:]

numBuyers = buyerPref.shape[0] #child is buyer
numFarmers = farmerPref.shape[0] #farmer is gift/santa
numFarmersPerBuyer = numBuyers / numFarmers #HEY LEANNA watch out - not every farmer is going to get matched

loading data...


/Users/leannamulvihill/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.
/Users/leannamulvihill/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [9]:

print(buyerPref)
# buyerPref = buyerPref.values()
print(type(buyerPref))
print(numFarmers)
print(numBuyers)

[[ 5.50078493  4.83411826  6.1674516   5.50078493  4.83411826  6.1674516
   5.50078493  6.94075353  6.27408687  5.6074202 ]
 [ 5.53330834  4.86664167  6.199975    5.53330834  4.86664167  6.199975
   5.53330834  7.12347207  6.4568054   5.79013873]
 [ 5.38725441  4.72058774  6.05392107  5.38725441  4.72058774  6.05392107
   5.38725441  6.30293196  5.63626529  4.96959863]
 [ 7.65217391  6.98550725  8.31884058  7.65217391  6.98550725  8.31884058
   7.65217391 16.         15.33333333 14.66666667]]
<class 'numpy.ndarray'>
9
4


In [28]:
#%% create lookup matrix
print('creating buyer vs. farmer value matrix...')
buyerPreferenceMatrix = -1*np.ones((numBuyers,numFarmers+1),np.float32)
for buyerID in range(numBuyers):
    for farmerOrder, farmID in enumerate(buyerPref[buyerID,:]):
        #buyerPreferenceMatrix[buyerID,farmID] = 2*(15 - farmerOrder)
        print(farmID)
        farmID = int(farmID) #farmID needs to be the index not the quantity
        print(buyerID)
        print(farmID)
        print(farmerOrder)
        buyerPreferenceMatrix[buyerID,farmerOrder] = (9 - farmID) #HEY LEANNA make it so that it reads the number of farmer and buyers from the file
        
        
farmerPreferenceMatrix = -1*np.ones((numBuyers,numFarmers+1),np.float32)
for farmID in range(numFarmers):
    for buyerOrder, buyerID in enumerate(farmerPref[farmID,:]):
        #farmerPreferenceMatrix[buyerID,farmID] = 2*(5 - buyerOrder)
        farmerPreferenceMatrix[buyerID,farmID] = (4 - buyerOrder)

#buyer_vs_farmer_matrix =  buyerPreferenceMatrix/(20.0*numBuyers)
buyer_vs_farmer_matrix =  buyerPreferenceMatrix/(numBuyers)
#buyer_vs_farmer_matrix += farmerPreferenceMatrix/(2000000.0*numFarmers)
buyer_vs_farmer_matrix += farmerPreferenceMatrix/(numFarmers)
buyer_vs_farmer_matrix = buyer_vs_farmer_matrix.astype(np.float32)

# del buyerPreferenceMatrix
# del farmerPreferenceMatrix

creating buyer vs. farmer value matrix...
5.5007849293563575
0
5
0
4.834118262689692
0
4
1
6.167451596023023
0
6
2
5.5007849293563575
0
5
3
4.834118262689692
0
4
4
6.167451596023023
0
6
5
5.5007849293563575
0
5
6
6.940753532182102
0
6
7
6.274086865515437
0
6
8
5.607420198848772
0
5
9
5.533308336457941
1
5
0
4.866641669791276
1
4
1
6.1999750031246075
1
6
2
5.533308336457941
1
5
3
4.866641669791276
1
4
4
6.1999750031246075
1
6
5
5.533308336457941
1
5
6
7.123472065991749
1
7
7
6.456805399325083
1
6
8
5.790138732658418
1
5
9
5.387254406362686
2
5
0
4.720587739696019
2
4
1
6.053921073029352
2
6
2
5.387254406362686
2
5
3
4.720587739696019
2
4
4
6.053921073029352
2
6
5
5.387254406362686
2
5
6
6.3029319583459715
2
6
7
5.636265291679305
2
5
8
4.969598625012639
2
4
9
7.6521739130434785
3
7
0
6.985507246376812
3
6
1
8.318840579710145
3
8
2
7.6521739130434785
3
7
3
6.985507246376812
3
6
4
8.318840579710145
3
8
5
7.6521739130434785
3
7
6
16.0
3
16
7
15.333333333333332
3
15
8
14.666666666666668
3
14

In [29]:
print(buyerPreferenceMatrix) #this looks good
print(farmerPreferenceMatrix) #does it make sense that this matrix is the same size as buyerPreferenceMatrix? Yes.
print(buyer_vs_farmer_matrix.shape) #looks good

[[ 4.  5.  3.  4.  5.  3.  4.  3.  3.  4.]
 [ 4.  5.  3.  4.  5.  3.  4.  2.  3.  4.]
 [ 4.  5.  3.  4.  5.  3.  4.  3.  4.  5.]
 [ 2.  3.  1.  2.  3.  1.  2. -7. -6. -5.]]
[[ 4.  3.  2.  1.  4.  3.  2.  1.  4. -1.]
 [ 3.  2.  1.  4.  3.  2.  1.  4.  3. -1.]
 [ 2.  1.  4.  3.  2.  1.  4.  3.  2. -1.]
 [ 1.  4.  3.  2.  1.  4.  3.  2.  1. -1.]]
(4, 10)


In [30]:
# scoring function
def calculateTotalHappiness(pred):
    totalHappiness = 0

    for i in range(numBuyers):
        buyer_id = i
        farmer_id = pred[i]
        totalHappiness += buyer_vs_farmer_matrix[buyer_id,farmer_id]
        
    return totalHappiness

In [31]:
def AssignFarmers_GreedyBuyers_Adaptive(buyer_vs_farmer_selection_matrix=buyer_vs_farmer_matrix, numPasses=15):
    buyer_vs_farmer_selection_matrix = buyer_vs_farmer_selection_matrix.copy()
    
    farmerAssignment = -np.ones((numBuyers), dtype=np.int32)
    farmerCount      = np.zeros((numFarmers),    dtype=np.int32)
    
    print('-'*40)
    startTime  = time.time()
            
    print('starting adaptive pass over the buyers')
    buyersPerPass = int(1+(numBuyers) / (numPasses+1.0))
    
    # at each pass we lower a threshold and assign gift to childern that are above the threshold
    for k in range(numPasses+1):
        # sort the children accroding to the maximum possible matrix value of each child
        maxValuePerBuyer = buyer_vs_farmer_selection_matrix.max(axis=1)
        sortedBuyers   = (maxValuePerBuyer.argsort())[::-1]
        
        thresholdBuyerInd   = numBuyers-1        
        assignmentThreshold = maxValuePerBuyer[thresholdBuyerInd]

        numAssignedSoFar = (farmerAssignment > -1).sum()        
        if (numAssignedSoFar > (0.99*numBuyers)) or (k >= (numPasses)):
            # make this last iteration
            assignmentThreshold = buyer_vs_farmer_selection_matrix.min() - 1.0
            thresholdBuyerInd = len(sortedBuyers)
            
        if numAssignedSoFar >= numBuyers:
            break
        
        for buyerInd in sortedBuyers[:thresholdBuyerInd]:
            # don't assign gifts unless high on priority list ( larger than 'assignmentThreshold' )
            if farmerAssignment[buyerInd] == -1 and buyer_vs_farmer_selection_matrix[buyerInd,:].max() >= assignmentThreshold:
                selectedFarmer = buyer_vs_farmer_selection_matrix[buyerInd,:].argmax()
        
                farmerAssignment[buyerInd] = selectedFarmer
                farmerCount[selectedFarmer] += 1
                
                if farmerCount[selectedFarmer] >= numFarmersPerBuyer:
                    buyer_vs_farmer_selection_matrix[:,selectedFarmer] = -1.0
                    
        print('pass %d: total assigned so far = %d' %(k+1,(farmerAssignment > -1).sum()))

    print('finished %d adaptive passes. took %.3f seconds' %(k+1, time.time()-startTime))
    assignmentScore = calculateTotalHappiness(farmerAssignment)
    print('-'*40)

    return farmerAssignment, assignmentScore

In [32]:
#%% normalize rows and columns of the assignment value matrix
print('normalizing rows and columns of the value matrix')
startingMatrix = buyer_vs_farmer_matrix.copy()
startingMatrix -= startingMatrix.min()
startingMatrix /= startingMatrix.max()

normalizing rows and columns of the value matrix


In [33]:
# create an assignment vector from the child vs. gift value matrix
print('assign farmers to buyers in a buyer centered greedy fashion')
pred, score = AssignFarmers_GreedyBuyers_Adaptive(startingMatrix, numPasses=16)
print('predicted score = %.8f' %(score))

assign farmers to buyers in a buyer centered greedy fashion
----------------------------------------
starting adaptive pass over the buyers
pass 1: total assigned so far = 3
pass 2: total assigned so far = 3
pass 3: total assigned so far = 3
pass 4: total assigned so far = 3
pass 5: total assigned so far = 3
pass 6: total assigned so far = 3
pass 7: total assigned so far = 3
pass 8: total assigned so far = 3
pass 9: total assigned so far = 3
pass 10: total assigned so far = 3
pass 11: total assigned so far = 3
pass 12: total assigned so far = 3
pass 13: total assigned so far = 3
pass 14: total assigned so far = 3
pass 15: total assigned so far = 3
pass 16: total assigned so far = 3
pass 17: total assigned so far = 4
finished 17 adaptive passes. took 0.002 seconds
----------------------------------------
predicted score = 5.33333325


In [34]:
#%% create a submission
out = open('heuristicSub.csv', 'w')
out.write('buyerId,farmId\n')
for i in range(len(pred)):
    out.write(str(i) + ',' + str(pred[i]) + '\n')
out.close()